# Generated by Django 6.0.6 on 2026-08-06 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_cinetpay_only'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cinetpay', 'CinetPay'), ('geniuspay', 'GeniusPay')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cinetpay', 'CinetPay'), ('geniuspay', 'GeniusPay')], max_length=20, null=True),
        ),
    ]
