# Generated by Django 6.0.6 on 2026-08-06 17:59

import apps.core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_transaction_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveSmallIntegerField()),
                ('ussd_code', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('assigned', 'Assignée'), ('dispatched', 'Envoyée'), ('executing', 'En cours'), ('success', 'Réussie'), ('failed', 'Échouée'), ('expired', 'Expirée')], default='assigned', max_length=20)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('raw_response', models.TextField(blank=True)),
                ('failure_reason', models.CharField(blank=True, choices=[('insufficient_balance', 'Solde insuffisant'), ('invalid_number', 'Numéro invalide'), ('network_error', 'Erreur réseau'), ('timeout', 'Délai dépassé'), ('unknown', 'Inconnue')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='gateway',
            name='battery_level',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gateway',
            name='max_concurrent_tasks',
            field=models.PositiveSmallIntegerField(default=apps.core.models._default_max_concurrent_tasks),
        ),
        migrations.AddField(
            model_name='refund',
            name='method',
            field=models.CharField(blank=True, choices=[('provider_auto', 'Automatique (fournisseur)'), ('manual', 'Manuel')], max_length=20),
        ),
        migrations.AddField(
            model_name='refund',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='refund',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_refunds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='refund',
            name='provider_refund_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
