# Generated by Django 6.0.6 on 2026-08-06 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_transactionattempt_gateway_battery_level_and_more'),
        ('devices', '0002_gatewaysim'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionattempt',
            name='gateway_sim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attempts', to='devices.gatewaysim'),
        ),
        migrations.AddField(
            model_name='transactionattempt',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='core.transaction'),
        ),
        migrations.AddIndex(
            model_name='transactionattempt',
            index=models.Index(fields=['status'], name='core_transa_status_1c0ffa_idx'),
        ),
        migrations.AddConstraint(
            model_name='transactionattempt',
            constraint=models.UniqueConstraint(fields=('transaction', 'attempt_number'), name='unique_transaction_attempt_number'),
        ),
    ]
