# Generated by Django 6.0.6 on 2026-08-06 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_transactionattempt_gateway_sim_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gateway',
            name='app_version',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='gateway',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gateway',
            name='is_busy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gateway',
            name='network_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='gateway',
            name='ram_available_mb',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gateway',
            name='reported_task_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gateway',
            name='signal_strength',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gateway',
            name='storage_available_mb',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gateway',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
