# Generated by Django 6.0.6 on 2026-08-06 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_gateway_app_version_gateway_ip_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='next_retry_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TransactionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.transaction')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['transaction', 'created_at'], name='core_transa_transac_7b8971_idx')],
            },
        ),
    ]
