# Generated by Django 6.0.6 on 2026-08-20 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_transaction_next_retry_at_transactionevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='UssdCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('template', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ussd_codes', to='core.operator')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ussd_codes', to='core.service')),
            ],
            options={
                'ordering': ['operator__name', 'service__name', 'label'],
                'indexes': [models.Index(fields=['operator', 'service', 'is_active'], name='core_ussdco_operato_7dc225_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('operator', 'service'), name='unique_active_ussd_code_per_operator_service')],
            },
        ),
    ]
