# Generated by Django 6.0.6 on 2026-08-22 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_service_is_active'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ussdcode',
            name='unique_active_ussd_code_per_operator_service',
        ),
        migrations.AddField(
            model_name='transaction',
            name='ussd_code_used',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_used_in', to='core.ussdcode'),
        ),
        migrations.AddField(
            model_name='ussdcode',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddConstraint(
            model_name='ussdcode',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('operator', 'service', 'amount'), name='unique_active_ussd_code_per_operator_service_amount', nulls_distinct=False),
        ),
    ]
