# Generated by Django 6.0.6 on 2026-08-23 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_transaction_idempotency_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='gateway',
            name='api_key_hash',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
