# Generated by Django 6.0.6 on 2026-08-24 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_gateway_api_key_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='UssdStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('step_type', models.CharField(choices=[('INPUT', 'Saisie'), ('FINAL_FIELD', 'Fin de saisie (attendre le résultat opérateur)')], default='INPUT', max_length=20)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('ussd_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='core.ussdcode')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UssdStepField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('field_type', models.CharField(choices=[('FIXED', 'Valeur fixe'), ('DYNAMIC', 'Variable dynamique')], max_length=10)),
                ('value', models.CharField(max_length=100)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='core.ussdstep')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddIndex(
            model_name='ussdstep',
            index=models.Index(fields=['ussd_code', 'order'], name='core_ussdst_ussd_co_fd1e94_idx'),
        ),
        migrations.AddConstraint(
            model_name='ussdstep',
            constraint=models.UniqueConstraint(fields=('ussd_code', 'order'), name='unique_step_order_per_ussd_code'),
        ),
        migrations.AddConstraint(
            model_name='ussdstepfield',
            constraint=models.UniqueConstraint(fields=('step', 'order'), name='unique_field_order_per_step'),
        ),
    ]
