# Generated by Django 6.0.6 on 2026-08-24 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_ussd_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionattempt',
            name='current_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attempts_at_this_step', to='core.ussdstep'),
        ),
        migrations.AddField(
            model_name='transactionattempt',
            name='last_step_idempotency_key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='transactionattempt',
            name='last_step_response',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
