# Generated by Django 6.0.6 on 2026-08-27 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_transaction_attempt_step_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('auto', 'Automatique (relais)'), ('cinetpay', 'CinetPay'), ('feexpay', 'FeexPay'), ('geniuspay', 'GeniusPay')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('auto', 'Automatique (relais)'), ('cinetpay', 'CinetPay'), ('feexpay', 'FeexPay'), ('geniuspay', 'GeniusPay')], max_length=20, null=True),
        ),
    ]
