# Generated by Django 6.0.6 on 2026-08-31 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('auto', 'Automatique (relais)'), ('jeko', 'Jèko'), ('geniuspay', 'GeniusPay')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('auto', 'Automatique (relais)'), ('jeko', 'Jèko'), ('geniuspay', 'GeniusPay')], max_length=20, null=True),
        ),
    ]
