# Generated by Django 6.0.6 on 2026-09-18 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_organize_ussd_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='ussdcode',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='ussdstep',
            name='step_type',
            field=models.CharField(choices=[('INPUT', 'Saisie'), ('AGENT_AUTH', 'Authentification agent / Code distributeur (secret local Gateway)'), ('FINAL_FIELD', 'Fin de saisie (attendre le résultat opérateur)')], default='INPUT', max_length=20),
        ),
    ]
