# Generated by Django 6.0.6 on 2026-08-27 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OtpCode',
        ),
    ]
