# Generated by Django 6.0.6 on 2026-08-28 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneOtp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, max_length=20)),
                ('code_hash', models.CharField(max_length=128)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='emailverificationcode',
            name='accounts_em_email_03cbb4_idx',
        ),
        migrations.DeleteModel(
            name='EmailVerificationCode',
        ),
        migrations.AddIndex(
            model_name='phoneotp',
            index=models.Index(fields=['phone_number', 'created_at'], name='accounts_ph_phone_n_23b4c6_idx'),
        ),
    ]
