# Generated by Django 6.0.6 on 2026-08-06 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_alter_payment_method_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('message', models.CharField(max_length=160)),
                ('purpose', models.CharField(choices=[('otp', 'Code de vérification'), ('notification', 'Notification')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('sent', 'Envoyé'), ('failed', 'Échoué')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('gateway', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_tasks', to='core.gateway')),
            ],
        ),
    ]
