# Generated by Django 6.0.6 on 2026-08-06 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_transactionattempt_gateway_battery_level_and_more'),
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GatewaySim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msisdn', models.CharField(blank=True, max_length=20)),
                ('slot', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('failure_count', models.PositiveIntegerField(default=0)),
                ('consecutive_failures', models.PositiveSmallIntegerField(default=0)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sims', to='core.gateway')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gateway_sims', to='core.operator')),
            ],
            options={
                'indexes': [models.Index(fields=['operator', 'is_active'], name='devices_gat_operato_346b83_idx')],
                'constraints': [models.UniqueConstraint(fields=('gateway', 'slot'), name='unique_gateway_slot')],
            },
        ),
    ]
