from django.urls import path
from . import views

urlpatterns = [
    path('login/', views.dashboard_login, name='dashboard_login'),
    path('logout/', views.dashboard_logout, name='dashboard_logout'),
    path('', views.dashboard_index, name='dashboard'),
    path('transactions/', views.transactions_list, name='transactions'),
    path('transactions/<int:pk>/', views.transaction_detail, name='transaction_detail'),
    path('paiements/', views.payments_list, name='payments'),
    path('remboursements/', views.refunds_list, name='refunds'),
    path('gateways/', views.gateways_list, name='gateways'),
    path('gateways/<int:pk>/toggle/', views.gateway_toggle, name='gateway_toggle'),
    path('sim/', views.gateway_sims_list, name='sims'),
    path('sim/<int:pk>/toggle/', views.sim_toggle, name='sim_toggle'),
    path('scheduler/', views.scheduler_monitor, name='scheduler'),
    path('operateurs/', views.operators_list, name='operators'),
    path('operateurs/nouveau/', views.operator_create, name='operator_create'),
    path('operateurs/<int:pk>/modifier/', views.operator_edit, name='operator_edit'),
    path('operateurs/<int:pk>/supprimer/', views.operator_delete, name='operator_delete'),
    path('operateurs/<int:pk>/codes/', views.ussd_codes_list, name='ussd_codes'),
    path('operateurs/<int:pk>/codes/nouveau/', views.ussd_code_create, name='ussd_code_create'),
    path('operateurs/historique/', views.operators_history, name='operators_history'),
    path('services/', views.services_list, name='services'),
    path('services/nouveau/', views.service_create, name='service_create'),
    path('services/<int:pk>/modifier/', views.service_edit, name='service_edit'),
    path('services/<int:pk>/supprimer/', views.service_delete, name='service_delete'),
    path('codes-ussd/', views.ussd_codes_all, name='ussd_codes_all'),
    path('codes/<int:pk>/modifier/', views.ussd_code_edit, name='ussd_code_edit'),
    path('codes/<int:pk>/supprimer/', views.ussd_code_delete, name='ussd_code_delete'),
    path('codes/<int:pk>/toggle/', views.ussd_code_toggle, name='ussd_code_toggle'),
    path('codes/apercu/', views.ussd_code_preview, name='ussd_code_preview'),
    path('clients/', views.clients_list, name='clients'),
    path('rapports/', views.reports_list, name='reports'),
    path('notifications/', views.notifications_list, name='notifications'),
    path('parametres/', views.settings_view, name='settings'),
    path('audit/', views.audit_logs, name='audit'),
    path('sante/', views.system_health, name='system_health'),
]
