# Generated by Django 6.0.6 on 2026-08-06 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=20)),
                ('event_id', models.CharField(max_length=150)),
                ('event_type', models.CharField(blank=True, max_length=50)),
                ('signature', models.TextField(blank=True)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('payment_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('processed', models.BooleanField(default=False)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['provider', 'payment_reference'], name='payments_we_provide_efeaae_idx')],
                'unique_together': {('provider', 'event_id')},
            },
        ),
    ]
